### ISSUE TITLE
Android client exception when i try to encrypt

### ISSUE THREAD

**Issue by AyoubOuarrak** [SinapsiProject/Sinapsi#3]
java.lang.NoSuchMethodError: org.apache.commons.codec.binary.Base64.encodeAsString

**Comment by ParsleyJ** [comment]
Try to use this: http://developer.android.com/reference/android/util/Base64.html

If the encryption phase is in BGP, probably you have to give the possibility to set a different encodeAsString method through a callback in your library.

**Comment by ParsleyJ** [comment]
updated to bgp 2.0 and fixed
